services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./contracts/deployed_contracts.json:/app/deployed_contracts.json:ro
      - ./scripts:/app/scripts:ro
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./fundchain.db
      - RPC_URL=http://anvil:8545
      - WEB3_PROVIDER_URL=http://anvil:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CONTRACT_ADDRESSES_FILE=/app/deployed_contracts.json
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8001,http://127.0.0.1:8001
      - API_KEY_SECRET=dev_secret_key_change_in_production
      - PRIVACY_K_THRESHOLD=5
      - TREASURY_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PROJECTS_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
      - GOVERNANCE_SBT_ADDRESS=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
      - BALLOT_ADDRESS=0x90F79bf6EB2c4f870365E785982E1f101E93b906
      - MULTISIG_ADDRESS=0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
    depends_on:
      - anvil
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped

  anvil:
    build:
      context: .
      dockerfile: anvil.Dockerfile
    ports:
      - "8545:8545"
    environment:
      - FOUNDRY_DISABLE_NIGHTLY_WARNING=true
    command: --port=8545 --accounts=10 --balance=10000 --chain-id=31337 --gas-limit=30000000
    restart: unless-stopped

  contracts:
    build:
      context: ./contracts
      dockerfile: Dockerfile
    volumes:
      - ./contracts:/app
      - contract_artifacts:/app/out
      - ./contracts/deployed_contracts.json:/app/deployed_contracts.json
    environment:
      - RPC_URL=http://anvil:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    depends_on:
      - anvil
    profiles:
      - deploy
    command: >
      sh -c "
        echo 'Waiting for Anvil to be ready...' &&
        sleep 5 &&
        forge script script/Deploy.s.sol --rpc-url http://anvil:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast
      "

volumes:
  contract_artifacts:

networks:
  default:
    name: fundchain_network